export { default as FooterComponent } from "./Footer/FooterComponent";
export { default as Arrivals } from './newArrivals/Arrivals';
export { default as FashionComponent } from './FashionComponent/Component';
export { default as BeautyComponent} from './Section3/BeautyComponent';
export { default as BestSellers } from './BestSellers/BestSellers';
export { default as FamousBrands } from './Section5/FamousBrands';
export { default as TopComponent } from './header/top/TopComponent';
export { default as HeaderCotegory }from './header/Cotegory/HeaderCotegory';
export { default as  Navbar } from './header/MainNavbar/Navbar';
export { default as CopyRight} from './Footer/CopyRight/CopyRight';